name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: GithubPackage
    permissions:
      contents: read
      packages: write
    runs-on: windows-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Publish on Github Release
      - name: Publish PowerShell Script
        uses: natescherer/publish-powershell-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: packages
          path: fortune.ps1